#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/izzat/Projects/Kenguroo/kangaroo-partner/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/izzat/Projects/Kenguroo/kangaroo-partner/kenguroo_partner"
export "FLUTTER_TARGET=/Users/izzat/Projects/Kenguroo/kangaroo-partner/kenguroo_partner/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/izzat/Projects/Kenguroo/kangaroo-partner/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=2.2.0"
export "FLUTTER_BUILD_NUMBER=14"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
